<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Bitfield.Core</RootNamespace>
    <AssemblyName>Bitfield.Core</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
    <Version>1.0.1</Version>
    <Product>Bitfield Torrent</Product>
    <Company>szabolevi98</Company>
    <Copyright>Copyright (c) 2026 szabolevi98</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bitfield.Tests" />
  </ItemGroup>

</Project>
